#!/usr/bin/env bash

# Setups the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

# Create virtual environment if not already in one
if [ ! -n "$VIRTUAL_ENV" ]; then
  if [ ! -d ".venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv .venv
  fi
  
  echo "Activating virtual environment..."
  source .venv/bin/activate
fi

# Install dependencies
echo "Installing dependencies..."
python3 -m pip install --upgrade pip
python3 -m pip install --requirement requirements.txt

echo "Setup complete!"
